//
// Created by yisus on 8/3/26.
//

#ifndef MONITORSYSTEM_PROBABILITYTYPE_H
#define MONITORSYSTEM_PROBABILITYTYPE_H

#include <third_party/ollama.hpp>

enum ProbabilityType { LOG_PROBABILITY, PROBABILITY, DEFAULT };

NLOHMANN_JSON_SERIALIZE_ENUM(ProbabilityType, {
    {LOG_PROBABILITY, "LOG_PROBABILITY"},
    {PROBABILITY,     "PROBABILITY"},
    {DEFAULT,         "DEFAULT"},
})

#endif //MONITORSYSTEM_PROBABILITYTYPE_H