//
// Created by yisus on 8/3/26.
//

#ifndef MONITORSYSTEM_PROBABILITYTYPE_H
#define MONITORSYSTEM_PROBABILITYTYPE_H

enum ProbabilityType { LOG_PROBABILITY, PROBABILITY, DEFAULT };
#endif //MONITORSYSTEM_PROBABILITYTYPE_H