# Usage: cmake -DINPUT_FILE=<path> -DOUTPUT_FILE=<path> -P EmbedFile.cmake
file(READ "${INPUT_FILE}" content HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${content}")
file(WRITE "${OUTPUT_FILE}"
"// Auto-generated by cmake/EmbedFile.cmake — do not edit manually\n"
"#pragma once\n"
"#include <string_view>\n"
"namespace embedded {\n"
"static const unsigned char prompt_data_raw[] = {${bytes}0x00};\n"
"static const std::string_view prompt_data(\n"
"    reinterpret_cast<const char*>(prompt_data_raw),\n"
"    sizeof(prompt_data_raw) - 1\n"
");\n"
"} // namespace embedded\n"
)